# Generated by Django 5.2.5 on 2025-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='image',
            field=models.ImageField(default=1, upload_to='container_images/'),
            preserve_default=False,
        ),
    ]
