# Generated by Django 5.2.5 on 2025-08-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_package_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='wigth',
            new_name='weight',
        ),
    ]
