# Generated by Django 5.2.5 on 2025-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_container_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='id',
        ),
        migrations.RemoveField(
            model_name='container',
            name='image',
        ),
        migrations.AlterField(
            model_name='container',
            name='container_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
